// =============================================================================
// log2_energy.sv  --  NEW, Luke Mouawad (R-A4; also used by audio_gate for dB)
// -----------------------------------------------------------------------------
// Unsigned integer x  ->  unsigned fixed-point y = log2(x), format Q(INT_W).(FRAC_W)
//
//   integer part : p = floor(log2 x)  = position of the leading one
//   fraction     : log2(1 + m), m = the bits below the leading one, from a
//                  65-entry LUT (Q0.12) indexed by the top 6 bits of m with
//                  linear interpolation on the next REM_W = 6 bits.
//                  Max error of the fraction before rounding < 5e-5.
//   rounding     : fraction rounded half-up from 12 bits to FRAC_W bits.
//   x == 0       : y = 0 and zero = 1 (log2(0) is undefined; treated as 1).
//   saturation   : if rounding carries past the largest code, y = all ones.
//
// Clock/reset domain : any (used in BCLK by audio_gate, FFT clock by the
//                      R-A4 path). Synchronous active-high reset.
// Handshake          : in_valid / out_valid, no back-pressure.
// Throughput/latency : one input per clock, LATENCY = 3 clocks.
// Constraint         : FRAC_W <= 12.
// =============================================================================
module log2_energy #(
    parameter int IN_W   = 48,
    parameter int FRAC_W = 10,
    parameter int INT_W  = $clog2(IN_W)          // holds 0 .. IN_W-1
) (
    input  logic                     clk,
    input  logic                     reset,
    input  logic [IN_W-1:0]          x,
    input  logic                     in_valid,
    output logic [INT_W+FRAC_W-1:0]  y,
    output logic                     out_valid,
    output logic                     zero
);
    localparam int IDX_W   = 6;                  // LUT index bits (64 segments)
    localparam int REM_W   = 6;                  // interpolation bits
    localparam int PAD     = 1 + IDX_W + REM_W;  // guarantees enough mantissa bits
    localparam int MW      = IN_W + PAD;
    localparam int Y_W     = INT_W + FRAC_W;
    localparam int RND_SH  = 12 - FRAC_W;                     // Q0.12 -> Q0.FRAC_W
    localparam int RND_HALF = (RND_SH > 0) ? (1 << (RND_SH - 1)) : 0;

    // ---------------- LUT: round(log2(1 + i/64) * 4096), i = 0..64 ----------
    // Generated by tools/audio/gen_audio_tables.py
    function automatic logic [12:0] log2_lut(input logic [6:0] i);
        case (i)
            7'd0:  log2_lut = 13'd0;    7'd1:  log2_lut = 13'd92;
            7'd2:  log2_lut = 13'd182;  7'd3:  log2_lut = 13'd271;
            7'd4:  log2_lut = 13'd358;  7'd5:  log2_lut = 13'd445;
            7'd6:  log2_lut = 13'd530;  7'd7:  log2_lut = 13'd613;
            7'd8:  log2_lut = 13'd696;  7'd9:  log2_lut = 13'd778;
            7'd10: log2_lut = 13'd858;  7'd11: log2_lut = 13'd937;
            7'd12: log2_lut = 13'd1016; 7'd13: log2_lut = 13'd1093;
            7'd14: log2_lut = 13'd1169; 7'd15: log2_lut = 13'd1244;
            7'd16: log2_lut = 13'd1319; 7'd17: log2_lut = 13'd1392;
            7'd18: log2_lut = 13'd1465; 7'd19: log2_lut = 13'd1536;
            7'd20: log2_lut = 13'd1607; 7'd21: log2_lut = 13'd1677;
            7'd22: log2_lut = 13'd1746; 7'd23: log2_lut = 13'd1814;
            7'd24: log2_lut = 13'd1882; 7'd25: log2_lut = 13'd1949;
            7'd26: log2_lut = 13'd2015; 7'd27: log2_lut = 13'd2080;
            7'd28: log2_lut = 13'd2145; 7'd29: log2_lut = 13'd2208;
            7'd30: log2_lut = 13'd2272; 7'd31: log2_lut = 13'd2334;
            7'd32: log2_lut = 13'd2396; 7'd33: log2_lut = 13'd2457;
            7'd34: log2_lut = 13'd2518; 7'd35: log2_lut = 13'd2578;
            7'd36: log2_lut = 13'd2637; 7'd37: log2_lut = 13'd2696;
            7'd38: log2_lut = 13'd2754; 7'd39: log2_lut = 13'd2812;
            7'd40: log2_lut = 13'd2869; 7'd41: log2_lut = 13'd2926;
            7'd42: log2_lut = 13'd2982; 7'd43: log2_lut = 13'd3037;
            7'd44: log2_lut = 13'd3092; 7'd45: log2_lut = 13'd3146;
            7'd46: log2_lut = 13'd3200; 7'd47: log2_lut = 13'd3254;
            7'd48: log2_lut = 13'd3307; 7'd49: log2_lut = 13'd3359;
            7'd50: log2_lut = 13'd3412; 7'd51: log2_lut = 13'd3463;
            7'd52: log2_lut = 13'd3514; 7'd53: log2_lut = 13'd3565;
            7'd54: log2_lut = 13'd3615; 7'd55: log2_lut = 13'd3665;
            7'd56: log2_lut = 13'd3715; 7'd57: log2_lut = 13'd3764;
            7'd58: log2_lut = 13'd3812; 7'd59: log2_lut = 13'd3861;
            7'd60: log2_lut = 13'd3908; 7'd61: log2_lut = 13'd3956;
            7'd62: log2_lut = 13'd4003; 7'd63: log2_lut = 13'd4050;
            default: log2_lut = 13'd4096;   // i = 64
        endcase
    endfunction

    // ---------------- Stage 1: leading-one detector --------------------------
    logic [INT_W-1:0] p_c;
    always_comb begin
        p_c = '0;
        for (int j = 0; j < IN_W; j++)
            if (x[j]) p_c = INT_W'(j);
    end

    logic [IN_W-1:0]  x1;
    logic [INT_W-1:0] p1;
    logic             v1, z1;
    always_ff @(posedge clk) begin
        if (reset) begin
            v1 <= 1'b0; x1 <= '0; p1 <= '0; z1 <= 1'b0;
        end else begin
            v1 <= in_valid;
            x1 <= x;
            p1 <= p_c;
            z1 <= (x == '0);
        end
    end

    // ---------------- Stage 2: normalise (leading one -> MSB), LUT index -----
    /* verilator lint_off UNUSEDSIGNAL */   // leading one and bits below the LUT/interp field are not needed
    logic [MW-1:0]    m_c;
    /* verilator lint_on UNUSEDSIGNAL */
    always_comb m_c = {x1, {PAD{1'b0}}} << (INT_W'(IN_W - 1) - p1);

    logic [IDX_W-1:0] idx2;
    logic [REM_W-1:0] rem2;
    logic [INT_W-1:0] p2;
    logic             v2, z2;
    always_ff @(posedge clk) begin
        if (reset) begin
            v2 <= 1'b0; idx2 <= '0; rem2 <= '0; p2 <= '0; z2 <= 1'b0;
        end else begin
            v2   <= v1;
            idx2 <= m_c[MW-2 -: IDX_W];
            rem2 <= m_c[MW-2-IDX_W -: REM_W];
            p2   <= p1;
            z2   <= z1;
        end
    end

    // ---------------- Stage 3: interpolate, round, saturate ------------------
    logic [12:0]        lo_c, hi_c;
    logic [6:0]         d_c;                     // adjacent LUT gap <= 92
    logic [12:0]        frac12_c;                // Q0.12, 0 .. 4095
    logic [13:0]        frac_rnd_c;              // FRAC_W bits + carry
    logic [Y_W:0]       sum_c;
    always_comb begin
        lo_c       = log2_lut({1'b0, idx2});
        hi_c       = log2_lut({1'b0, idx2} + 7'd1);
        d_c        = 7'(hi_c - lo_c);
        frac12_c   = lo_c + 13'((14'(d_c) * 14'(rem2)) >> REM_W);
        frac_rnd_c = (14'(frac12_c) + 14'(RND_HALF)) >> RND_SH;
        sum_c      = ((Y_W+1)'(p2) << FRAC_W) + (Y_W+1)'(frac_rnd_c);
    end

    always_ff @(posedge clk) begin
        if (reset) begin
            out_valid <= 1'b0; y <= '0; zero <= 1'b0;
        end else begin
            out_valid <= v2;
            zero      <= z2;
            if (z2)            y <= '0;
            else if (sum_c[Y_W]) y <= '1;         // rounding overflow -> saturate
            else               y <= sum_c[Y_W-1:0];
        end
    end
endmodule
